# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cJumXTtL6AHrvedvbKT97fmMWTPeF_Lx
"""

films = ("Матрица" , "темный рыцарь" , "матрица 2" , "начало")

matrix_films = [film for film in films if 'Матрица' in film]

print(matrix_films)